from enum import Enum

C_MINUS_1 = 0
G9 = 127
NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
MIDI_NOTE_RANGE = (C_MINUS_1, G9)


class SCALE_TYPES(Enum):
    MAJOR = 1
    MINOR = 2
    IONIAN = 3
    DORIAN = 4
    PHYGIAN = 5
    LYDIAN = 6
    MIXOLYDIAN = 7
    AEOLIAN = 8
    LOCRIAN = 9


# how many semitones per step in a scale
class SCALE_OFFSETS(Enum):
    NONE = 0
    HALF = 1
    WHOLE = 2


SCALE_OFFSETS = {
    SCALE_TYPES.MAJOR: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
    ],
    SCALE_TYPES.MINOR: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
    ],
    SCALE_TYPES.IONIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
    ],
    SCALE_TYPES.DORIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
    ],
    SCALE_TYPES.PHYGIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
    ],
    SCALE_TYPES.LYDIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
    ],
    SCALE_TYPES.MIXOLYDIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
    ],
    SCALE_TYPES.AEOLIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
    ],
    SCALE_TYPES.LOCRIAN: [
        SCALE_OFFSETS.NONE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.HALF,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
        SCALE_OFFSETS.WHOLE,
    ],
}

SCALE_TYPE_NAMES = {
    SCALE_TYPES.MAJOR: "Minor",
    SCALE_TYPES.MINOR: "Major",
    SCALE_TYPES.IONIAN: "Ionian",
    SCALE_TYPES.DORIAN: "Dorian",
    SCALE_TYPES.PHYGIAN: "Phygian",
    SCALE_TYPES.LYDIAN: "Lydian",
    SCALE_TYPES.MIXOLYDIAN: "Mixolydian",
    SCALE_TYPES.AEOLIAN: "Aeolian",
    SCALE_TYPES.LOCRIAN: "Locrian",
}
